<?xml version="1.0"?>

<robot name="qev2" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="robot_namespace" default="/" />

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find qutms_autonomous)/urdf/wheel_front.urdf.xacro" />
  <xacro:include filename="$(find qutms_autonomous)/urdf/wheel_rear.urdf.xacro" />

  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="2.165" />
  <xacro:property name="base_y_size" value="0.735" />
  <xacro:property name="base_z_size" value="0.63" />
 
  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="1.2" />
  <xacro:property name="track" value="1.2" />
  <xacro:property name="wheel_vertical_offset" value="0.1" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1524" />
  <xacro:property name="wheel_radius" value="0.1651" />

  <xacro:macro name="qev2_body">

    <!-- Chassis -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0.4" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.4" rpy="0 0 0"  />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </collision>
    </link>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
          <origin xyz="0 0 0.4" rpy="0 0 0" />
          <mass value="46" />
          <inertia ixx="3.5923125" ixy="0" ixz="0" iyy="19.4891458333" iyz="0" izz="20.0385583333" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- QEV2 wheel macros -->

    <!-- Front -->
    <xacro:qev2_wheel_front wheel_prefix="left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:qev2_wheel_front>
    <xacro:qev2_wheel_front wheel_prefix="right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:qev2_wheel_front>

    <!-- Rear -->
    <xacro:qev2_wheel_rear wheel_prefix="left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:qev2_wheel_rear>
    <xacro:qev2_wheel_rear wheel_prefix="right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:qev2_wheel_rear>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>$(arg robot_namespace)</robotNamespace>
      </plugin>
    </gazebo>

    <gazebo reference="base_link">
			<material>Gazebo/Grey</material>
		</gazebo>

  </xacro:macro>

</robot>
