qev2_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

qev2_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  
  publish_rate: 50

  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']

  # Odometry covariances for the encoder output of the robot. These values should
  # be tuned to your robot's sample odometry data, but these values are a good place
  # to start
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 1.2
  wheel_radius : 0.1651

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0
 
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Top level frame (link) of the robot description
  base_frame_id: base_link

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 10.0   # m/s
      has_acceleration_limits: false
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 10   # rad/s
      has_acceleration_limits: false
      max_acceleration       : 25.0   # rad/s^2
